version: '3.8'
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-ai-assistant
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
      - ./qa_chain.py:/app/qa_chain.py
      - ./document_processor.py:/app/document_processor.py
      - ./assets:/app/assets
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    user: "1005:1005"